# Answer 1:

In [8]:
import numpy as np
arr=np.arange(2,50,3)
print("Array of all the integers from 2 to 50 with a stepsize of 3")
print(arr) 

Array of all the integers from 2 to 50 with a stepsize of 3
[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Answer 2:

In [34]:
import numpy as np
 
# initilizing lists
list1 = [4, 2, 5, 3, 1]
list2 = [9, 8, 6, 10, 7]
 
# converting lists into arrays
arr1 = np.array(list1)
arr2 = np.array(list2)
 
#Concatenation of arrays
arr_c = np.concatenate((arr1, arr2))
print(arr_c)

#Sorting of arrays
print(np.sort(arr_c))

 

[ 4  2  5  3  1  9  8  6 10  7]
[ 1  2  3  4  5  6  7  8  9 10]


# Answer 3:

In [ ]:
'''To get the number of dimensions, shape (size of each dimension) and size (number of all elements) of NumPy array, 
use attributes ndim, shape, and size of numpy.ndarray. The built-in function len() returns the size of the first dimension.

Number of dimensions of numpy.ndarray: ndim
Shape of numpy.ndarray: shape
Size of numpy.ndarray (total number of elements): size
Size of the first dimension of numpy.ndarray: len()'''

In [46]:
import numpy as np
arr_x=np.array([[2, 3, 4, 5],[1, 0, 4, 7]])

dim_x = arr_x.ndim 
print (dim_x) 

length_x = len(arr_x)
print(length_x)

2
2


# Answer 4:

In [47]:
import numpy as np
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr_1d, (2, 5), order='F')
print('2D Numpy array:')
print(arr_2d)

2D Numpy array:
[[0 2 4 6 8]
 [1 3 5 7 9]]


# Answer 5:

In [12]:
import numpy as np

a=np.square([1,2,3,4,5])
b=np.square([6,7,8,9,10])

# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b))) 
 

Vertical stacking:
 [[  1   4   9  16  25]
 [ 36  49  64  81 100]]

Horizontal stacking:
 [  1   4   9  16  25  36  49  64  81 100]
