# Numpy Assignment

In [32]:
import numpy as np 
m = np.array([[1, 2], [2, 3]])  
print("Printing the Original square array:\n", m) 
w, v = np.linalg.eig(m) 
print("Printing the Eigen values of the given square array:\n", w) 
print("Printing Right eigenvectors of the given square array:\n", v)

Printing the Original square array:
 [[1 2]
 [2 3]]
Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [3]:
import numpy as np  
a = np.array([1.2, 2.4, 3.6, 4.8]) 
bins = np.array([1.0, 1.3, 2.5, 4.0, 10.0]) 
# using np.digitize() method 
syed = np.digitize(a, bins) 
print(syed)

[1 2 3 4]


In [33]:
import numpy as np
arr = np.arange(5) 
print("arr : \n", arr) 
  
repetitions = 2
a = np.repeat(arr, repetitions) 
print("\nRepeating arr 2 times : \n", a) 
print("Shape : ", a.shape) 
  
repetitions = 3
a = np.repeat(arr, repetitions) 
print("\nRepeating arr 3 times : \n", a) 
print("Shape : ", a.shape) 

arr : 
 [0 1 2 3 4]

Repeating arr 2 times : 
 [0 0 1 1 2 2 3 3 4 4]
Shape :  (10,)

Repeating arr 3 times : 
 [0 0 0 1 1 1 2 2 2 3 3 3 4 4 4]
Shape :  (15,)


In [5]:
import numpy as np 
in_arr = np.array([[[2, 2, 2], [2, 2, 2]]]) 
print ("Input array : ", in_arr)  
print("Shape of input array : ", in_arr.shape)   
out_arr = np.squeeze(in_arr)  
print ("output squeezed array : ", out_arr) 
print("Shape of output array : ", out_arr.shape)  

Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)
output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)


In [6]:
import numpy as np 
print("B\n", np.linspace(2.0, 3.0, num=5, retstep=True), "\n") 
x = np.linspace(0, 2, 10) 
print("A\n", np.sin(x)) 

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [7]:
import numpy as np 
in_array = [1, 2, 3, 4, 5, 6, 7, 8 ] 
print ("Input array : ", in_array) 
out_array = np.clip(in_array, a_min = 2, a_max = 6) 
print ("Output array : ", out_array)

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
Output array :  [2 2 3 4 5 6 6 6]


In [34]:
import numpy as np 
array = np.arange(10).reshape(5, 2) 
print("Original array : \n", array) 
  
a = np.mod(array, 4) !=0
# This will show element status of satisfying condition 
print("\nArray Condition a : \n", a) 
  
# This will return elements that satisy condition "a" condition 
print("\nElements that satisfy condition a  : \n", np.extract(a, array)) 

b = array - 4 == 1
# This will show element status of satisfying condition 
print("\nArray Condition b : \n", b) 
  
# This will return elements that satisy condition "b" condition 
print("\nElements that satisfy condition b  : \n", np.extract(b, array)) 

Original array : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Array Condition a : 
 [[False  True]
 [ True  True]
 [False  True]
 [ True  True]
 [False  True]]

Elements that satisfy condition a  : 
 [1 2 3 5 6 7 9]

Array Condition b : 
 [[False False]
 [False False]
 [False  True]
 [False False]
 [False False]]

Elements that satisfy condition b  : 
 [5]


In [35]:
import numpy as np
  
# input array 
in_arr = np.array([[ 2, 0,  1], [ 5, 4, 9] ]) 
print ("Input array : \n", in_arr)  
  
out_arr = np.argpartition(in_arr, 1, axis = 1) 
print ("Output partitioned array indices :\n ", out_arr) 

Input array : 
 [[2 0 1]
 [5 4 9]]
Output partitioned array indices :
  [[1 2 0]
 [1 0 2]]


In [36]:
import numpy as np  
arr1 = [5, 6, 2, 3, 4] 
arr2 = [1, 2, 3] 
x = np.setdiff1d(arr1, arr2) 
print (x) 

[4 5 6]


In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype = np.float64) 
y = array.itemsize
print (y) 


4


In [15]:
import numpy as np 
  
in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [16]:
import numpy as np 
  
# input array 
in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays vertically 
out_arr = np.vstack((in_arr1, in_arr2)) 
print ("Output vertically stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


In [22]:
import numpy as np  
 
a = np.arange(9).reshape(3, 3) 
  
print("The array {} gets splitted \ horizontally to form {} ".format(a, np.hsplit(a, 3))) 
  
print("The array {} gets splitted \ horizontally to form {} ".format(a, np.split(a, 3, 1)))


The array [[0 1 2]
 [3 4 5]
 [6 7 8]] gets splitted \ horizontally to form [array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])] 
The array [[0 1 2]
 [3 4 5]
 [6 7 8]] gets splitted \ horizontally to form [array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])] 


In [21]:
import numpy as np 
a = np.arange(9).reshape(3, 3) 
print("The array {} gets splitted \ vertically to form {} ".format(a, np.vsplit(a, 3))) 
print("The array {} gets splitted \ vertically to form {} ".format(a, np.split(a, 3, 0))) 

The array [[0 1 2]
 [3 4 5]
 [6 7 8]] gets splitted \ vertically to form [array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])] 
The array [[0 1 2]
 [3 4 5]
 [6 7 8]] gets splitted \ vertically to form [array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])] 


In [24]:
import copy 
  
list = [1, 2, [3,5], 4] 
  
# using copy for shallow copy   
List1 = copy.copy(list)  
print(List1)

[1, 2, [3, 5], 4]


In [25]:
import copy 

list = [1, 2, [3,5], 4] 

# using deepcopy for deepcopy   
List1 = copy.deepcopy(list)
print(List1)

[1, 2, [3, 5], 4]


In [26]:
import numpy as np 
 
x = np.array([[0, 1, 2, 3], [4, 5, 6, 7]],  order ='F') 
print("x is: \n", x) 
  
# copying x to y 
y = x.copy() 
print("y is :\n", y) 
print("\nx is copied to y")


x is: 
 [[0 1 2 3]
 [4 5 6 7]]
y is :
 [[0 1 2 3]
 [4 5 6 7]]

x is copied to y


In [28]:
import numpy as np 
 
x = np.linspace(-4, 4, 9) 
  
y = np.linspace(-5, 5, 11) 
  
x_1, y_1 = np.meshgrid(x, y) 
  
print("x_1 = ") 
print(x_1) 
print("y_1 = ") 
print(y_1)

x_1 = 
[[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]]
y_1 = 
[[-5. -5. -5. -5. -5. -5. -5. -5. -5.]
 [-4. -4. -4. -4. -4. -4. -4. -4. -4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.]]


In [30]:
import numpy as np           
a = np.matrix('[4, 1; 12, 3]')             
b = a.swapaxes(0, 1) 
print(b)

[[ 4 12]
 [ 1  3]]


In [31]:
import numpy as np
x = np.array((3,4,5))
y = np.array((4,5,6))
np.column_stack((x,y))

array([[3, 4],
       [4, 5],
       [5, 6]])